---
- name: Install Filebeat dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true
  become: true

- name: Download Elastic GPG key
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: "0644"
  become: true

- name: Install Elastic GPG key
  ansible.builtin.shell: |
    gpg --dearmor --yes \
      -o /usr/share/keyrings/elasticsearch-keyring.gpg \
      /tmp/GPG-KEY-elasticsearch
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  become: true

- name: Add Elastic repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://mirror.yandex.ru/mirrors/elastic/9/ stable main"
    filename: elastic-9.x
    state: present
  become: true

- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
    update_cache: true
  become: true

- name: Deploy Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0600"
  become: true
  notify: Restart Filebeat

- name: Enable and start Filebeat
  ansible.builtin.service:
    name: filebeat
    enabled: true
    state: started
  become: true
