all:
  children:
    web:
      hosts:
        web-1:
          ansible_host: 10.10.20.15

        web-2:
          ansible_host: 10.10.40.4

    monitoring:
      children:
        prometheus:
          hosts:
            prometheus:
              ansible_host: 10.10.20.35

        grafana:
          hosts:
            grafana:
              ansible_host: 10.10.10.9
