---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart Nginx Log Exporter
  ansible.builtin.service:
    name: prometheus-nginxlog-exporter
    state: restarted
  become: true
